---
# Docker daemon security handlers
- name: Restart Docker daemon
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true

- name: Restart stack
  ansible.builtin.systemd:
    name: stack
    state: restarted
    daemon_reload: true

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted
    daemon_reload: true

