- name: Configure VPS
  hosts: vps
  become: true
  gather_facts: false
  vars_files:
    - group_vars/vps.yml
    - group_vars/vps.vault.yml
  vars:
    ansible_user: "{{ admin_user }}"
    ansible_port: "{{ ssh_port }}"
    ansible_ssh_private_key_file: "{{ vps_ssh_private_key_file }}"
  tasks:
    - import_role:
        name: security
      tags: security

    - import_role:
        name: docker
      tags: docker

    - import_role:
        name: deploy_stack
      tags: deploy_stack